# Site settings
title: 
header-img: img/home-bg.png
email: tgbrown@stanford.edu
copyright_name: tristangerardbrown
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tristangerardbrown
learn_profile: tristangerardbrown
email_username: tgbrown@stanford.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
